EducationalTestingService/rsmtool

conda-recipe/unix/rsmtool/meta.yaml
conda-recipe/windows/rsmtool/meta.yaml
doc/CHANGELOG.md
rsmtool/version.py

- This fixes the `rsmcompare` issue of accidentally swapping the old and the new experiments.

v5.0.1 hot fix release

---

LICENSE

Discovered missing when comparing to output of the `lice` tool.
part of JOSS review:
https://github.com/openjournals/joss-reviews/issues/33

Fix License to actually declare copyright

---

rsmtool/notebooks/comparison/header.ipynb
rsmtool/notebooks/header.ipynb
rsmtool/report.py

- Use `notebook_path` in `report.py` when constructing new paths.
- Explicitly read `javascript/sort.js` in both header notebooks to get around weird encoding issues in RSMApp.

Fix the loading of Javascript sorting library in header notebooks.

---

rsmtool/preprocess.py

When testing whether feature sd in the training set is zero, we currently set tolerance to 1-06. This was not sufficient with features with very low values (these can result from an inverse transform of acoustic likelihoods which are logs of very small values and therefore very large themselves).
As long as RSMTool is able to do the standardization, the tolerance does not affect other outputs.

Lowered the tolerance for standard deviation to 1-07

---

circle.yml

The latest version of `miniconda` apparently does two things differently now:
- it unzips packages and leaves those directories under `pkgs`. Since we explicitly cache `pkgs` to ensure fast builds, the existing directories cause conflicts. I guess previously it was ignoring existing directories. 
- it now installs packages in the root conda environment that are _not_ available for python 3.4 at all which causes problems when we use the root environment for installing rsmtool. We now create an entirely new environment (`rsmenv`) and use that instead of the root environment.

Fix CircleCI builds

---

rsmtool/writer.py
tests/test_writer.py

In some cases, it may be useful to pass a dictionary to the `DataWriter` `write_experiment_output()` method, rather than having to instantiate a `DataContainer` object. 
This PR addresses issue #159. It also incorporates a new test to check that a `dict` can be passed to `write_experiment_output()`.

Allow dictionary to to be passed to `DataWriter` `write_experiment_output()` method

---

rsmtool/preprocessor.py
tests/test_preprocessor.py

Just a small PR to address issue #184.

Allow `lists` to be passed to `trim()`

---

tests/test_experiment_rsmcompare.py
tests/test_experiment_rsmeval.py
tests/test_experiment_rsmpredict.py
tests/test_experiment_rsmsummarize.py
tests/test_experiment_rsmtool_1.py
tests/test_experiment_rsmtool_2.py
tests/test_experiment_rsmtool_3.py
tests/test_experiment_rsmtool_4.py

For package testing, we want to be able to run tests that are located outside of the package. This PR allows that.  To test that this works:
1. Check out `master` and `pip install -e .` that in a new conda environment (say `rsmenv`).
2. Check out this branch separately into a separate directory (say `$RSMNEWDIR`). Make some change to  `tests/data/experiments/lr/output/lr_betas.csv` but don't commit it.
3. Go to $HOME
4. Activate `rsmenv` and run `TESTDIR=$RSMNEWDIR nosetests --nologcapture $RSMNEWDIR/tests/test_experiment_rsmtool_1.py`. The `lr` experiment test should now fail. This tells us that the test data is now being used from the given `TESTDIR` instead of from the installed version of RSMTool in the environment.

Allow specification of the tests directory via an environment variable

---

rsmtool/analyzer.py
rsmtool/utils.py
tests/test_utils.py

This PR addresses #217. It creats adds a separate `standardized_mean_difference()` function that can be called outside `rsmtool`.
**Note:** This PR should not be reviewed until after #220 is reviewed.

Add separate SMD function

---

rsmtool/configuration_parser.py
rsmtool/container.py
tests/test_configuration_parser.py
tests/test_container.py

This is a small PR to address the following:
- Adds `pop()` and `copy()` methods to `Configuration` class (issue #233).
- Adds `context` setter to `Configuration` class.
- Updates `copy()` method in `Container` class to use Python's `copy` library instead.
- Adds tests for all of the above.
None of these updates are required for the operation of `rsmtool`, but could be useful for the API.

Add methods to `Configuration` and update `copy()` in `Container`

---

doc/config_rsmtool.rst
doc/tutorial_rsmpredict.rst
rsmtool/configuration_parser.py
rsmtool/preprocessor.py
tests/test_configuration_parser.py

* Fixed few typos in documentation and messages (#193)
* Based on feedback, added further detail about the use of `flag_column_test` and updated the code to indicate partition when checking the flag column (#211). @jbiggsets please check this does not break any of your code.

Typos in documentation

---

DistributeTests.ps1
azure-pipelines.yml
tests/test_reader.py

Addresses #308. 
- Add `azure-pipelines.yml` file to configure the build system on Azure.
- Add` DistributeTests.ps1` powershell script to divide up tasks on 5 parallel agents just like Travis CI.

Integrate testing on Windows using Azure Pipelines

---

doc/pipeline.rst

* Added a note to documentation that default tolerance changed in the 7.0 which will lead to different outputs in some cases. 
Addresses #313

Add note about trim_tolerance to the documentation

---

environment.yml
requirements.txt

This is a PR to address the failing builds resulting from the following error:
```
ERROR: ipython 7.10.1 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.18 which is incompatible.
``` 
For now, we just pin `jupyter_console` to version `6.0.0`. However, we'll want to remove `jupyter_console` from the requirements list once this incompatibility is resolved. See issue #323 for more details.

Fix build versions

---

environment.yml
requirements.txt

- `jupyter_console` gets installed automatically so no need to explicitly pin it to get around some weird conda packaging issue (see #323).
- No need to pin `ipython``, notebook`, and `statsmodels` since they are relatively stable and not likely to change their interfaces.
- Pin `pandas` in `environment.yml` just like we do in `requirements.txt`.
- Add `seaborn` to `environment.yml`

Clean up and align `requirements.txt` and `environment.yml` 

---

environment.yml
requirements.txt
rsmtool/test_utils.py
tests/test_experiment_rsmtool_3.py
tests/test_experiment_rsmtool_4.py

As discussed in #351, the current solution is to simply suppress the convergence warnings coming from scikit-learn until we can pass in custom values for SKLL hyperparameters.
In addition, I also made it much simpler to add future suppression warnings for tests based on `run_experiment`. I modified `check_run_experiment()` and `do_run_experiment()`  to accept a list of warning types as a keyword argument. This will allow any types of warnings to be suppressed and doesn't require adding individual `filterwarnings()` in each test.

Suppress convergence warnings for LinearSVR test (Also make future warning suppression easier)

---

rsmtool/configuration_parser.py
rsmtool/utils.py
tests/test_analyzer.py
tests/test_experiment_rsmtool_1.py
tests/test_test_utils.py
tests/test_utils.py

* This PR partially addresses #352 : I added comments to tests that are expected to raise warnings and warning capture/test to make sure these are handled correctly. 
* We are now catching all `warnings` but none of the logger warnings. See #367 for further discussion:  we need to decide on how to treat these before we make further changes to tests.

352 capture expected warnings in tests

---

.coveragerc
.travis.yml
DistributeTests.ps1
azure-pipelines.yml
rsmtool/test_utils.py
tests/test_configuration_parser.py
tests/test_experiment_rsmcompare.py
tests/test_experiment_rsmeval.py
tests/test_experiment_rsmpredict.py
tests/test_experiment_rsmsummarize.py
tests/test_experiment_rsmtool_3.py
tests/test_test_utils.py

[This line](https://github.com/EducationalTestingService/rsmtool/blob/master/rsmtool/test_utils.py#L34) that computes `rsmtool_test_dir` basically assumes that the tests are always being run from the RSMTool source code directory. However, this is not true when we are testing the conda/pip packages (which do not include the tests). We currently use the `TESTDIR` environment variable to get around this but this does not always work as this PR shows (many of the tests still rely on `rsmtool_test_dir` directly). However, for now, this PR provides a fix for such tests.
This PR:
1. Add the missing test file `test_test_utils.py` to Travis and Azure builds.
2. Modify `copy_data_files()` and some other test functions to explicitly specify `rsmtool_test_dir`so that the tests pass when running the …

Make tests run with package and add missing test file

---

rsmtool/configuration_parser.py
rsmtool/modeler.py
rsmtool/preprocessor.py
rsmtool/reporter.py
rsmtool/rsmcompare.py
rsmtool/rsmeval.py
rsmtool/rsmpredict.py
rsmtool/rsmsummarize.py
rsmtool/rsmtool.py
rsmtool/utils.py
tests/test_configuration_parser.py
tests/test_experiment_rsmcompare.py
tests/test_experiment_rsmeval.py
tests/test_experiment_rsmpredict.py
tests/test_experiment_rsmsummarize.py
tests/test_experiment_rsmtool_3.py

**[Note: This PR supersedes #386].**
In our discussions, we recently found `configuration_parser.py` to be significantly over-engineered and a bit unwieldy to use. This PR attempts to fix that via a refactoring of the two main classes: `Configuration` and `ConfigurationParser`. There are also resulting changes to tests and other modules. Specifically:
1. The `Configuration` class is now instantiated using a dictionary so there's no need for special methods to deal with dictionaries. 
2. `ConfigurationParser` is now used only to parse configuration files (JSON or CFG). You create an instance for a given file and then call `.parse()` that returns a `Configuration` instance. The methods `normalize_config()`, `process_config()`, and `validate_config()` are all now class methods that accept a …

Refactor `configuration_parser.py`

---

.travis.yml
azure-pipelines.yml
rsmtool/utils/commandline.py
tests/test_cli.py

This PR fixes #401. 
It does so by adding a workaround for the `defaults` keyword argument for `collections.namedtuple` that is only supported in Python 3.7+.  It also replaces the `capture_output` keyword argument for `subprocess.run()` calls that is used in `test_cli.py`.
It also make sure that Travis CI builds use Python 3.6 and that Azure ones use Python 3.8. This ensures that we are covering the two Python versions most important to us - 3.6 for internal use and the latest (3.8) for external use.
*Update*: 3.8 support is broken right now (see #403). So, we have to make do with Python 3.7 instead of 3.8 in Azure.

Fix CmdOption on Python 3.6

---

doc/automated_configuration.rst
doc/contributing.rst
rsmtool/configuration_parser.py
rsmtool/utils/commandline.py
tests/test_cli.py
tests/test_utils.py

This PR closes #422 and closes #424.
- Add `-i` as an alias for `--interactive`.
- Add `-g` as an alias for `--subgroups`.
- Add some new tests for these short flags.
- Update documentation to introduce these short flags.
- Add explicit note about subgroups to interactive mode instructions.
- Capture STDERR in CLI tests to enable easier debugging when tests error out.
- Remove some imports that were no longer necessary.
**Note**: I didn't update the screencasts since the only thing that changed was the extra note about subgroups and I didn't think it was worth it to redo them.

Interactive configuration feature requests

---

rsmtool/configuration_parser.py
rsmtool/preprocessor.py
tests/test_configuration_parser.py
tests/test_preprocessor.py

This PR closes #389  and closes #408.
- Explicitly drop column in `FeaturePreprocessor.filter_on_column()`  if it's fully non-numeric and show informative message.
- Tweak some pandas code to make it more efficient.
- Tweak the existing test to test for dropped columns.
- Add an explicit check if a directory is passed as input to `ConfigurationParser.__init__()` and raise an `OSError`.
- Add tests for `ConfigurationParser.__init__()` in `test_configuration_parser.py`.
- Standardize all the exception messages in that method. 
- Improve the doctoring for the method.

Two minor fixes.

---

rsmtool/notebooks/consistency.ipynb
rsmtool/notebooks/true_score_evaluation.ipynb

This PR addresses #315 .
If the `consistency` and `true_score_evaluations` are included into the report, the headers will now always be displayed. If there is no `second_human_score`, the report shows that no data was available. The user can always exclude those sections from the list if they don't want to see empty headers.

Display headers for consistency and PRMSE notebooks

---

tests/test_cli.py
tests/test_utils.py
tests/test_utils_prmse.py

Modify `test_utils.py`, `test_cli.py`, and `test_utils_prmse.py` to respect the `TESTDIR` environment variable which is used to run tests with conda and PyPI packages.

Set test directory based on environment variable first

---

doc/internal/release_process.rst
rsmtool/version.py

- Update version number.
- Update numpy version in conda build instructions.
Conda and PyPI package already built and uploaded. Package testing builds passing.

RSMTool v8.0.1 Release PR

---

README.rst
rsmtool/configuration_parser.py
rsmtool/version.py

- Update version number
- Remove stray colon from a docstring.
- Add Azure pipelines badge to README (closes #439). 
The conda package has been built and is [live](https://anaconda.org/ets/rsmtool). The test builds for this package on both [Linux](https://travis-ci.org/github/EducationalTestingService/rsmtool-conda-tester) and [Windows](https://dev.azure.com/EducationalTestingService/RSMTool%20Conda%20Tester/_build/results?buildId=919&view=results) are passing. 
The PyPI package was built and uploaded to the [TestPyPI sandbox](https://test.pypi.org/project/rsmtool). The test builds for this package on both [Linux](https://travis-ci.org/github/EducationalTestingService/rsmtool-pip-tester) and [Windows](https://dev.azure.com/EducationalTestingService/RSMTool%20TestPyPI%20Tester/_build/result …

V8.0.2 release

---

.readthedocs.yml
.travis.yml
README.rst
doc/getting_started.rst
requirements.txt
rsmtool/utils/commandline.py

Same changes as #498 but applied to `main` instead of `stable`.

Drop python3.6 support in main.

---

rsmtool/utils/files.py
tests/test_utils.py

Regex to remove comments from JSON file in parse_json_with_comments was incorrectly matching URLs like "https://...". 
Fixed by adding negative lookbehind to regex.
Added additional unit tests for parse_json_with_comments
Closes #492.

Fixed Regex in parse_json_with_comments

---

doc/internal/release_process.rst

Documenting scenario where changes are made to input and output test files like linearsvr. This in turn affects rsmcompare and rsmsummarize so the test files have to be updated.

Add steps to release docs for more clarity

---

rsmtool/test_utils.py
tests/test_analyzer.py

This PR closes #536 and closes #538.
* Refactored test setup to avoid performance warning
* No changes were necessary for #538 since warnings came from third package. 
* Added a note to developers to flag the duplicate warning tracking (see also #539)

538 warnings in reports

---

doc/internal/release_process.rst
rsmtool/version.py

Not a lot of changes - basically the version change.
[rsmtool-pip-tester](https://github.com/EducationalTestingService/rsmtool-pip-tester/pull/12) and [rsmtool-conda-tester](https://github.com/EducationalTestingService/rsmtool-conda-tester/pull/15) PRs are both passing.

v8.1.2 Release

---

rsmtool/notebooks/comparison/header.ipynb
rsmtool/notebooks/comparison/model.ipynb
rsmtool/notebooks/header.ipynb
rsmtool/notebooks/summary/header.ipynb

This PR resolves #553. 
Adding `use_thumbnails = true` to a configuration file was generating both the thumbnail as well as the full-sized figure. The solution was to turn off interactive plotting in all header notebooks. 
To review, please run 2 `rsmxval` experiments:  one that uses `use_thumbnails`  and one that doesn't. Make sure that the figures show up as expected in all the reports in both experiments. Please also try an `rsmcompare` experiment separately since that is not part of `rsmxval`.

Fix `use_thumbnails` option.

---

rsmtool/notebooks/fairness_analyses.ipynb

Compute confidence intervals using absolute values so that we don't compute negative ones that pandas & Matplotlib complain about.

Disallow negative confidence intervals.

---

rsmtool/reporter.py

Newer versions of nbconvert use a "clean_html" filter on SVG elements that break SVG rendering; so we override that filter here with a custom function that is essentially a noop. For more details, please refer to #571. 
To review this properly, please run the following on **both your Macs and on a Linux server** (EC2 instance will work too):
- Clone RSMTool and switch to this branch
- If you are running on your Mac, run `CONDA_SUBDIR=osx-64 mamba create -n rsmdev --file requirements.txt python=3.8` to create the conda environment. If on a Linux server, run `mamba create -n rsmdev --file requirements.txt python=3.8` instead.
-  Activate the newly created environment and run `pip install -e .`
- Run `rsmtool tests/data/experiments/lr-subgroups-with-h2/lr_subgroups_with_h2.json foobar`. 
- …

Add workaround for broken SVGs in nbconvert

---

rsmtool/fairness_utils.py

Closes #579. 
Numpy v1.24 removes the `warnings` alias so we need to use `warnings` directly in `fairness_utils.py`.

Remove `np.warnings` from `fairness_utils.py`.

---

doc/api.rst
rsmtool/__init__.py
rsmtool/modeler.py
rsmtool/preprocessor.py
rsmtool/rsmpredict.py
rsmtool/test_utils.py
tests/test_experiment_rsmpredict.py
tests/test_modeler.py

Closes #546. 
The current method that `rsmpredict` uses is called `compute_and_save_prediction()` and is meant for batch prediction – it reads files from disks, does a lot of validation, and writes the predictions to disk. Therefore, it is not suited for real-time prediction on single instances which needs to happen in memory. 
This PR adds a new function called `fast_predict()` to `rsmpredict.py` meant to run on a single data point rather than a batch. This function expects the user to have already read all of the necessary files from disk (e.g., in a RFS service's `setup()` function) and simply pass the in-memory data structures to this function. This function then pre-processes the features, generates predictions for the single data point using the model, and then post-processes the …

Add new `fast_predict()` API method for prediction

---

.gitignore
doc/config_rsmexplain.rst.inc
rsmtool/rsmexplain.py
tests/test_experiment_rsmexplain.py
tests/test_explanation_utils.py

- Assume that `sample_ids` are now actual example IDs instead of indices.
- Raise a `ValueError` if anything goes wrong in `select_examples`.
- Update `test_explanation_utils.py`    
- Use actual string IDs in the test data.
- Update all expected outputs to use these new string IDs.
- Update relevant test in `test_experiment_rsmexplain.py` to IDs. 
- Update rsmexplain documentation
- Update description of `sample_ids` and move it to the end.
- Fix some typos.
Closes #609.

Use example IDs when specifying `sample_ids`

---

rsmtool/test_utils.py
tests/update_files.py

- Refactor `test_utils.FileUpdater.run` for `nose2` 
- Replace `nosetests` with `nose2`  in `update_files` comments and messages. 
Closes #615.

Fix `update_files` for `nose2`. 

---

rsmtool/fairness_utils.py
rsmtool/notebooks/comparison/header.ipynb
rsmtool/notebooks/explanations/header.ipynb
rsmtool/notebooks/header.ipynb
rsmtool/notebooks/summary/header.ipynb

- Update the header notebooks for all tools to exclude the matplotlib and tqdm warnings that were being shown in all the reports.
- Replace unnecessary use of `resetwarnings()` with the `catch_warnings()` context manager in `fairness_utils.py`.  This is necessary to ensure that the filtering of warnings in notebooks works as expected.
To test this, please check out the branch, run an experiments for each of the command-line tools, and confirm that no warnings are shown in the reports.
This PR closes #618.

Remove unnecessary warnings in HTML reports.

---

doc/config_rsmexplain.rst.inc
rsmtool/notebooks/explanations/shap_values.ipynb
rsmtool/reporter.py

Temporarily change the log level of the `HTMLExporter` instance to suppress the warning of the type "WARNING: Alternative text missing on XX image(s)". 
To test, run all of the tutorials and make sure that there are no warnings of the above type printed out on the terminal. 
Closes #626.

Suppress alt text warnings when generating reports

---

.coveragerc
.gitlab-ci.yml
DistributeTests.ps1
tests/test_wandb.py

- Fix broken `wandb` test.
- Add missing `test_wandb` to both CI builds. 
- Remove non-code files from coverage computation by fixing `.coveragerc`. 
Closes #635.

Fix W&B tests and add to CI builds.

---

.coveragerc
.isort.cfg
.pre-commit-config.yaml
.ruff.toml
rsmtool/modeler.py
tests/test_utils.py

- Update pre-commit checks to use `ruff` instead of `flake8`, `isort`, and `pydocstyle`.  
- Add `.ruff.toml` file and remove `.isort.cfg` file. 
- Fix case in one of the docstrings. 
- Update `.coveragerc` to exclude unneeded file.
- Add new unit test to increase coverage. 
Closes #629.

Switch to `ruff` for pre-commit checks

---

rsmtool/modeler.py
rsmtool/rsmpredict.py
tests/test_experiment_rsmpredict.py

Deal with situation where trimming, scaling, etc., modeler attributes exist but are `None`, which would be the case when loading an older model (bare SKLL model).
Even if these attributes were `None` before, it would still have led to an error somewhere down the line (`TypeError` if `trim_min` and `trim_tolerance` were `None` and/or a mixture of `None` and `float`, for instance). This change should catch that and give a nicer error message.

Improvements to fast_predict validation/error handling

---

.pre-commit-config.yaml
doc/contributing.rst

This PR:
- updates the pre-commit checks to their latest versions
- updates `contributing.md` to use correct pre-commit install command
To test this, check out this branch and run the command in `contributing.md`. Then try to make a commit with a random commit message, it should fail.

Update pre-commit checks

---

examples/rsmtool/config_rsmtool.json
rsmtool/analyzer.py
rsmtool/rsmeval.py
rsmtool/rsmtool.py
rsmtool/utils/wandb.py
tests/test_experiment_rsmtool_4.py
tests/test_wandb.py

- log all the values of the following tables as run metrics: `consistency`, `eval_short`, `true_score_eval`. This allows easy comparison between runs in the [runs view](https://wandb.ai/etslabs/rsmtool_tutorial/table?workspace=user-tamarlv)
- log confusion matrices as custom charts, this also allows comparing between runs - see in the [workspace view](https://wandb.ai/etslabs/rsmtool_tutorial/workspace?workspace=user-tamarlv)
@desilinguist @mulhod The changes make the tutorial run quite slow for me. Please test and let me know what you think.
to test add the following to `rsmtool` / `rsmeval` tutorial config (change project name accordingly), and run it in this branch:
``` 
"use_wandb": true,
"wandb_project": "rsmtool_tutorial",
"wandb_entity": "etslabs"
```

Enhance wandb logging of evaluation metrics

---

rsmtool/notebooks/consistency.ipynb
rsmtool/notebooks/evaluation.ipynb
rsmtool/utils/cross_validation.py
tests/test_utils.py

- fix the concatenation of prediction files from xval folds, which used the `keys` param incorrectly and unnecessarily. This caused a bug only with more than 9 folds.
- added a 10-fold scenario to the test of that method
- fixed the description of human-system confusion matrix to match the matrix axes values.
- changed the title of human-human confusion matrix to be different than the human-system one, so that the links at the top works correctly.

Bug fixes in xval and report

---

.gitlab-ci.yml
requirements.txt
rsmtool/rsmcompare.py
rsmtool/rsmeval.py
rsmtool/rsmexplain.py
rsmtool/rsmpredict.py
rsmtool/rsmsummarize.py
rsmtool/rsmtool.py
rsmtool/rsmxval.py
tests/test_cli.py

- All tools main functions now take arguments. This is needed to refactor the CLI tests so that they call the main functions directly instead of using subprocess calls.
- Refactor the CLI tests since we want to be able to use the command-line `codecov` tool which does not measure subprocess coverage.
- Switch to `codecov` binary in the Gitlab CI plan and install `curl` so we can download that binary in the first place.
- Ignore cleanup errors in `test_cli.py`.
Notes:
1. A side-benefit of this change is that `test_cli.py` now runs 3x faster since we aren't using subprocesses.
2. The coverage change is expected since we are changing the total number of lines in the code.
Closes #638.

Refactor CLI tests to modernize codecov

---

conda-recipe/rsmtool/meta.yaml
requirements.txt

This is to avoid any potential failures when numpy 2 comes out since it breaks backward compatibility.
Closes #671.

Pin numpy to < 2

---

doc/conf.py
doc/requirements.txt
requirements.txt
rsmtool/analyzer.py
rsmtool/comparer.py
rsmtool/configuration_parser.py
rsmtool/container.py
rsmtool/rsmeval.py
rsmtool/rsmexplain.py
rsmtool/rsmpredict.py
rsmtool/rsmsummarize.py
rsmtool/rsmtool.py
rsmtool/rsmxval.py

- Minor typos in docstrings.
- Add `sphinx-autodoc-typehints` dependency.
- Improve sphinx auto documentation.
- Add type hints to `container.py`
- Add type hints to `analyzer.py`
- Add type hints to `comparer.py`.
- Add type hints to `configuration_parser.py`
- Please check that I have not left any parameters/arguments/return values without type hints. 
- Here's the [RTD build for this branch](https://rsmtool.readthedocs.io/en/326-type-hints-2). Check the "API Documentation" section (only for the files affected by this MR and the previous one) to confirm that all types are linked to relevant pages from external documentations (e.g., Python, Numpy, SKLL). There's no W&B yet since it doesn't seem to work. I have a ticket open with them.
- Check for typos and/or weird issues in docstrings.

Add type hints (Part 2)

---

rsmtool/analyzer.py
rsmtool/reporter.py
rsmtool/rsmeval.py
rsmtool/rsmexplain.py
rsmtool/rsmpredict.py
rsmtool/rsmsummarize.py
rsmtool/rsmtool.py
rsmtool/rsmxval.py
rsmtool/test_utils.py
rsmtool/transformer.py
rsmtool/writer.py
tests/test_comparer.py
tests/test_experiment_rsmeval.py
tests/test_experiment_rsmpredict.py
tests/test_experiment_rsmtool_1.py
tests/test_experiment_rsmtool_2.py
tests/test_experiment_rsmtool_3.py
tests/test_experiment_rsmtool_4.py

- Add type hints to `reporter.py`
- Fix some typos in docstrings
- Add type hints to `test_utils.py`
- Add type hints to `transformer.py`
- Add type hints to `writer.py`.
- Fix incorrect number of transformer arguments.
- Remove unneeded argument from `rsmeval` tests.
- Please check that I have not left any parameters/arguments/return values without type hints.
- Here's the [RTD build for this branch](https://rsmtool.readthedocs.io/en/326-type-hints-4). Check the "API Documentation" section (for the files affected by this MR) to confirm that all types are linked to relevant pages from external documentations (e.g., Python, Numpy, SKLL, stats models etc.) and there are no typos etc. 
- Check for typos and/or weird issues in docstrings.

Add Type Hints (Part 4)

---

doc/conf.py
rsmtool/analyzer.py
rsmtool/reporter.py
rsmtool/rsmeval.py
rsmtool/rsmexplain.py
rsmtool/rsmpredict.py
rsmtool/rsmsummarize.py
rsmtool/rsmtool.py
rsmtool/test_utils.py
rsmtool/utils/commandline.py
rsmtool/utils/constants.py
rsmtool/utils/conversion.py
rsmtool/utils/cross_validation.py
rsmtool/utils/files.py
rsmtool/utils/logging.py
rsmtool/utils/metrics.py
rsmtool/utils/models.py
rsmtool/utils/notebook.py
rsmtool/utils/prmse.py
rsmtool/utils/wandb.py
rsmtool/writer.py
tests/test_utils.py

- Add intersphinx mapping for prompt_toolkit
- Add type hints for `utils.commandline`
- Add type hints for `utils.conversion`
- Add type hints for `utils.cross_validation`
- Add type hints for `utils.files`
- Add type hints for `utils.logging`
- Add type hints for `utils.metrics`
- Add type hints for `utils.models`
- Add type hints for `utils.notebook`
- Add type hints for `utils.prmse`.
- Add type hints for `utils.wandb`
- Please check that I have not left any parameters/arguments/return values without type hints.
- Please check that the types in the docstrings match those in the actual code. 
- Here's the [RTD build for this branch](https://rsmtool.readthedocs.io/en/326-type-hints-5). Check the "API Documentation" section (for the files affected by this MR) to confirm that all types are …

Add Type Hints (Final Part)
