EducationalTestingService/rsmtool

- rsmtool/model.py
> RSMR-206 #comment resolve [ci skip]

- rsmtool/rsmeval.py
- tests/data/experiments/lr-eval-same-system-human-score/lr_eval_same_system_human_score.json
- tests/test_experiment.py
- tests/test_input.py
An extra check in RSMeval that the column names for system and human scores are not the same.
> Check that system and human scores are not the same

- rsmtool/report.py
- otherwise things do not work correctly in RSMApp.
> Use explicit encoding in `merge_notebooks()`

- paper.bib
Per https://github.com/openjournals/joss-reviews/issues/33.
> Add DOI to Williamson paper

- .coveragerc
- README.md
- circle.yml
- conda_requirements.txt
- conda_requirements_windows.txt
- Integrate coveralls.io into CI tests.
> Add test coverage.

- rsmtool/__init__.py
- rsmtool/analysis.py
- rsmtool/model.py
- rsmtool/predict.py
- rsmtool/rsmpredict.py
Two issues remain when running pyflakes 1.2.3:
rsmtool/__init__.py:13: 'rsmextra' imported but unused
rsmtool/model.py:515: local variable 'intercept' is assigned to but never used
(1) is necessary to establish whether the module exists
(2) makes the code easier to read
> pyflakes issues

- conda-recipe/unix/rsmtool/meta.yaml
- conda-recipe/windows/rsmtool/meta.yaml
- rsmtool/version.py
1. Fix conda issues.
2. Merged PRs #49, #51, #55. 
3. Update version numbers.
> Release 5.1.1

- conda-recipe/rsmtool/meta.yaml
- rsmtool/version.py
> 5.5.2 Release 

- README.md
- conda-recipe/rsmtool/meta.yaml
- doc/contributing.rst
- doc/getting_started.rst
- doc/index.rst
- doc/release_process.rst
- rsmtool/version.py
- setup.py
- Update README.
- Update version numbers.
- Update conda recipe.
- Update installation command in documentation.
- Add release process to documentation.
> Release branch for v5.7

- rsmtool/__init__.py
- rsmtool/rsmcompare.py
- rsmtool/rsmeval.py
- rsmtool/rsmpredict.py
- rsmtool/rsmsummarize.py
- rsmtool/rsmtool.py
Adding rsmextra version to `--version`. This addresses issue #187.
> Add rsmextra version

- tests/test_utils.py
Minor update to treatment of paths in intermediate files tests
> Fix paths in intermediate files test

- conda-recipe/rsmtool/meta.yaml
- rsmtool/version.py
> Version 6.0.1 Release.

- doc/contributing.rst
> Fix typo in documentation

- rsmtool/preprocessor.py
- tests/data/experiments/lr-with-requested-feature-with-zero-sd/lr_with_requested_feature_with_zero_sd.json
- tests/test_experiment_rsmtool_4.py
> Raise error instead of warning when requested feature has zero variance.

- doc/config_rsmtool.rst
- doc/who.rst
As discussed, I updated the documentation to make sure we are using gender-neutral pronouns.
> Documentation update

- rsmtool/analyzer.py
- rsmtool/prmse_utils.py
- tests/test_prmse_utils.py
This PR includes the following updates:
1. Some minor formatting changes to `prmse_utls.py` to address linting issues.
2. Updates to `prmse_utls.py` to allow users to pass the names of the human score columns.
3. Some super nitpicky formatting changes to `analyzer.py` to address linting issues. (Method definitions inside a class should be surrounded by a single blank line, while functions should be surrounded by two blank lines, per [PEP 8](https://www.python.org/dev/peps/pep-0008/#blank-lines).)
> Some tweaks to the PRMSE branch

- .pep8speaks.yml
Testing out a potential pep8 checker integration from [pep8speaks.com](https://pep8speaks.com).
> Add pep8speaks integration.

- doc/evaluation.rst
- rsmtool/utils.py
- tests/test_analyzer.py
- tests/test_utils.py
Change QWK formula and associated tests (#296)
> 296 alternative qwk formula

- doc/conf.py
> Prevent resorting of import that would break RTD builds.

- .gitignore
- README.rst
- doc/getting_started.rst
- setup.py
- Update `README.rst` and `setup.py` to include Python 3.7 and 3.8.
- Add some text about interactive config generation video and link to the demo video.
- Add a getting started section heading to make things more readable.
> Tweak README file and setup.py

- .travis.yml
- README.rst
- doc/getting_started.rst
- requirements.txt
- rsmtool/utils/commandline.py
- Update Travis CI to use 3.7.
- Unpin IPython package in `requirements.txt`.
> Drop Python 3.6 support

- .readthedocs.yml
Forgot to remove Python 3.6 from `.readthedocs.yml`.
> Fix RTD build config.

- doc/internal/release_process.rst
- rsmtool/test_utils.py
- tests/test_cli.py
Made changes to suppress all warnings when not in STRICT mode instead of just deprecation warnings.
> Fix broken RSMTool CI build

- README.rst
Changed coverage badge from coveralls to codecov.
> Fixed coverage badge in README

- README.rst
- doc/contributing.rst
> Fixed broken link in README and added link to repo in docs

- doc/contributing.rst
- doc/internal/release_process.rst
Fixed errors in Contributing.rst:
1. Fixed numbering issue
2. Fixed code block so that warning text is displayed
More information was needed in step 2 of release_process.rst so added link to relevant section.
> Fixing typos in Contributing.rst and adding more information to release_process.rst

- doc/contributing.rst
- doc/internal/release_process.rst
> Changed numbered lists to # in contributing.rst and release_process.rst

- doc/internal/release_process.rst
- rsmtool/version.py
- Updated version number.
- Updated release docs.
> v8.1.1 Release

- rsmtool/analyzer.py
- rsmtool/preprocessor.py
- rsmtool/reader.py
- tests/test_analyzer.py
- tests/test_reader.py
This PR addresses #534 , #533  , and #531 
* Fixed test set up in TestAnalyzer
* Changed read_jsonlines to accommodate new behavior of `pd.normalize_json`
* Added "axis" keyword to instances of `pandas.dataframe.drop`
> Fix issues related to new Pandas version

- README.rst
- doc/internal/release_process.rst
- Update release process document.
- Update documentation badge in README.
> Make preparations for deleting the stable branch. 

- doc/config_rsmtool.rst.inc
- doc/intermediate_files_rsmeval.rst.inc
- doc/intermediate_files_rsmtool.rst.inc
A couple minor things I saw recently while reading the documentation.
> Minor documentations fixes

- README.rst
- conda-recipe/rsmtool/meta.yaml
- requirements.txt
> Update SHAP to the latest version 0.44.0

- MANIFEST.in
- README.rst
- conda-recipe/rsmtool/meta.yaml
- doc/internal/release_process.rst
- rsmtool/version.py
- tests/data/experiments/knn-explain/output/knn_rsmexplain.json
- tests/data/experiments/rf-explain/output/rf_rsmexplain.json
- tests/data/experiments/svr-explain-object/output/svr_explain_object_rsmexplain.json
- tests/data/experiments/svr-explain/output/svr_rsmexplain.json
- Update version numbers
- Update some test outputs
- Update documentation badge
- Exclude `tests` directory from PyPI and conda package
- Update conda build command in release process document
Passing builds for:
✅ [TestPyPI package](https://github.com/EducationalTestingService/rsmtool-pip-tester/pull/20)
✅ [Conda package](https://github.com/EducationalTestingService/rsmtool-conda-tester/pull/23)
Please test the conda package at the very least.
> v11.3.0 Release
